# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e47c70022228c7199816e651b15e683d9ffe47cd73d2f5972052c65d8966136c613b7357fb9eef99ef4e3c6a7c3765b6bd96e756f5d3d957bc521b43cd204e1a

test:
  secret_key_base: 896a48cae94e6af609a00a7a299ce4a1b4f6221d0ebefb48f604167be04270f8e626de661d31d8c1f94599c279af78d521fc3e395cf355a125f134621a3e9661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
